### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by m312z** [squirrel-project/squirrel_robotino#125]
When I run:
`rosdep install --from-path squirrel_robotino -i -y`

I get the output:

```
executing command [sudo -H apt-get install -y robotino-api2]
E: Unable to locate package robotino-api2
```

**Comment by ipa-nhg** [comment]
Unfortunately the robotino-api has to be extra installed, robotino-api2 is still not an official released ubuntu package  and requires the setup of the sources: http://wiki.openrobotino.org/index.php?title=Debrepository

To find a package with rosdep it has to be previously released and defined in rosdistro package: https://github.com/ros/rosdistro or you have to create your own private rosdistro dependencies. I am planning to create some installation scripts for the squirrel-project, I will consider this issue and try to find the package automatically.

Thanks @m312z

**Comment by m312z** [comment]
Thanks @ipa-nhg. I'm compiling everything from the review on my desktop and running into a few errors.

I followed the link you gave, ran `apt-get update` and installed robotino-api2 successfully. Now rosdep gives no errors. For now the extra steps could be added to the README until the scripts are ready.

Now I have a new error:

```
include/robotino_driver/MappingROS.h:4:39: fatal error: rec/robotino/api2/Mapping.h: No such file or directory
 #include "rec/robotino/api2/Mapping.h"

include/robotino_driver/MappingROS.h:4:39: fatal error: rec/robotino/api2/Mapping.h: No such file or directory
 #include "rec/robotino/api2/Mapping.h"
```

Any ideas?

Michael

**Comment by mzillich** [comment]
trying to reproduce ..

**Comment by ipa-nhg** [comment]
Maybe the robotino-api2 requires also some extra packages? try this: http://wiki.openrobotino.org/index.php?title=Install_daemons_v3 

We started with the documentation in squirrel_scenarios: https://github.com/squirrel-project/squirrel_scenarios/tree/indigo_dev/installation-prerequsites , but I will copy the information  to the README

**Comment by m312z** [comment]
I've tried robotino-common, tools, and examples already. "daemons" won't install as it depends upon missing robotino-config.

**Comment by ipa-nhg** [comment]
I am not able to reproduce the error. If you want to test the review software version, you will need  the arm package and it requires also the installation of the robotino api, but in this case, using the private dependencies. Try please this readme: https://github.com/squirrel-project/squirrel_robotino_arm/

**Comment by m312z** [comment]
I followed the instructions on that page, and have deleted devel and build directories to recompile everything from scratch.

The squirrel_robotino_arm package compiled successfully. I get the same error for squirrel_robotino:

```
src/squirrel_robotino/robotino_driver/include/robotino_driver/MappingROS.h:4:39: fatal error: rec/robotino/api2/Mapping.h: No such file or directory
 #include "rec/robotino/api2/Mapping.h"
```

(everything else compiles)

**Comment by mzillich** [comment]
Hi, I have the same error:

```
catkin_ws/src/squirrel_robotino/robotino_driver/include/robotino_driver/MappingROS.h:4:39: fatal error: rec/robotino/api2/Mapping.h: No such file or directory
 #include "rec/robotino/api2/Mapping.h"
```

This used to compile without problems.
@ipa-nhg can You find which package that missing file is in?

**Comment by ipa-nhg** [comment]
I am not able to reproduce the error, neither after reinstall the package..

Can you please check your robotino-api2 installation? The cmake_module_path point to `/usr/local/robotino/api2/cmake` and the header Mapping.h should be located: `/usr/local/robotino/api2/include/rec/robotino/api2/Mapping.h`

**Comment by mzillich** [comment]
`/usr/local/robotino/api2/include/rec/robotino/api2/Mapping.h` is not there. I have:

```
ii  robotino-api2                               1.0.2                                      amd64        Robotino API2
ii  robotino-common                             1.0.4                                      amd64        Robotino common components
ii  robotino-examples                           1.0.0                                      amd64        Robotino examples
ii  robotino-tools                              1.0.3                                      amd64        Robotino Tools
```

**Comment by ipa-nhg** [comment]
Ok, I am using a different mirror: `http://doc.openrobotino.org/download/packages/amd64`  and you are using `http://packages.openrobotino.org/trusty` 

I can check the differences between both of them, but the old one is the currently installed version on the robots

**Comment by ipa-nhg** [comment]
Some headers were deleted for the 1.0.2 version, our robotino_driver is at the moment not compatible  with this version. Please use the version 0.9.16:

Delete the file /etc/apt/sources.list.d/openrobotino.list and command:

```
echo "deb http://doc.openrobotino.org/download/packages/amd64 ./" >> /etc/apt/sources.list
sudo apt-get purge robotino-api2
sudo apt-get update 
sudo apt-get install robotino-api2
```

@florianvoigtlaender could you please help us to understand the differences between both versions and let us to know where can we find the compatible ROS drivers for the 1.0.2 robotino-api2 version?

**Comment by mzillich** [comment]
whoops, that cleared out my sources.list!
I guess it should be

```
echo "deb http://doc.openrobotino.org/download/packages/amd64 ./" >> /etc/apt/sources.list
```

**Comment by ipa-nhg** [comment]
Ups sorry, I modified  the comment

**Comment by florianvoigtlaender** [comment]
I contacted our expert for the robotino API2 - I will forward his answer as soon as it arrives.

**Comment by florianvoigtlaender** [comment]
By the way - I am currently upgrading our Robotino to the professional version. this means a complete fresh installation. Basically I should also experience this (or other) issues.

**Comment by ipa-nhg** [comment]
@florianvoigtlaender updates here?

**Comment by florianvoigtlaender** [comment]
Unfortunately no response from our expert so far...
- But I gathered some Infos myself: At a certain point (step from Fuerste to Hydro) in the development of the robotino API2, the support for the Microsoft Kinect camera was dropped. I think this also includes the Mapping capabilities and so on. 
  To compensate this feature drop, it is recommended to use the OpenNI packages instead for the funtionality. But I think this doesn´t help much, if we want to use the recent version of the API in the squirrel project.

**Comment by florianvoigtlaender** [comment]
For the sake of completeness - our expert (Dr. Verbeek) responded. 

English translation:
"The API2 is a Work-in-Progress and things change. Headers appear and disappear. 
I recommend to change the ros node. "

Orginial (German): 
"die Schnittstelle hat sich halt geändert. Das ist work in progress. Da fliegen manchmal header Dateien raus und andere kommen hinzu. Man muss die ROS node entsprechend anpassen."

**Comment by dexter-v** [comment]
I think the issue is still present. It only compiles with API version 0.9.16 or did I miss something?
