### ISSUE TITLE
Repositories reestructuration 

### ISSUE THREAD

**Issue by ipa-nhg** [squirrel-project/squirrel_robotino#131]
I would like to review our low level software structure now that we will get a new arm control driver.

I propose use:
- `squirrel_common` : for messages
- `squirrel_robotino` : for launch files (real robot and simulation) and yaml files (configuration)
- `squirrel_driver` : for all the drivers, actuators : base, arm, hand... and sensors: airskin, ft17...

The description of the components (URDF) could be moved to squirrel_common or  squirrel_driver (with the component driver), I only have a request, the package that contains the description should be public. A external user has to be able to test our simulation. 

@mzillich @bajo What do you think?

**Comment by ipa-nhg** [comment]
Move `robotino_driver,` `robotino_safety`and `robotino_teleop` to **squirrel_driver**.

Move `robotino_description` to **squirrel_common**.

**Comment by bajo** [comment]
@ipa-nhg Sounds reasonable to me.

**Comment by ipa-nhg** [comment]
https://github.com/squirrel-project/squirrel_robotino/pull/134

**Comment by ipa-nhg** [comment]
@bajo @mzillich 

https://github.com/squirrel-project/squirrel_robotino/pull/149
https://github.com/squirrel-project/squirrel_common/pull/132
https://github.com/squirrel-project/squirrel_driver/pull/52 (waiting for https://github.com/squirrel-project/squirrel_driver/pull/43)

With these 3 PR we finish the migration and integration of the new drivers, after merge the PR `squirrel_driver` can be public and buildbot can start the release process. 

The main changes were developed during the Y2.1 Integration Meeting, after the meeting the driver of the arm was improved(Innsbruck) and the simulation model adapted (IPA)

**Comment by mzillich** [comment]
great, thanks!

**Comment by ipa-nhg** [comment]
Done
