### ISSUE TITLE
fingers missing

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_robotino#168]
Running `robotino_bringup_sim` the robot comes up with arm, hand, fingers. But with `robotino_bringup` only the hand wrist is there, with some coupler thingies lying on the bottom (= inside) the robot. Do not simulation and real use the same xacro/urdf file?

**Comment by ipa-nhg** [comment]
the urdf is the same, URDF (robot_description) gives to ROS the tree of frames, parents/links and the origins . But to know the actual position of your links tf use the /joint_states topic, the driver of each actuator should publish the states of the joints , for simulation a gazebo plugin for ros_controllers, on the real hand the kclhand_control (I think this code https://github.com/squirrel-project/squirrel_kclhand/blob/03e0f5eb418d826591fbba027a87aa0a7c0a71b0/kclhand_control/src/state_publisher.cpp) , for me it looks like a calibration problem. 
For a 0,0,0,0... joint_states the hand should look like the urdf file defines:
![screenshot from 2017-01-18 13 00 45](https://cloud.githubusercontent.com/assets/650568/22063280/4919c624-dd7e-11e6-8381-9b436dfa482a.png)

**Comment by mzillich** [comment]
Exactly. With no running joint state publisher, I'd be happy to have random joint positions, but at least the coupler links and fingers should be attached to the hand.

**Comment by ipa-nhg** [comment]
I think this is important for moveit! , read the actual joint_states to know where are the links and prevent collisions... This issue should be solved or we have to ignore the fingers to plan trajectories...
