### ISSUE TITLE
double kclhand launch file

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_robotino#169]
@ipa-nhg There are two launch files for kcl hand:
>./robotino_bringup/launch/kclhand.launch
  ./robotino_bringup/robots/kcl-hand/launch/kcl-hand.launch

I guess there should be no kcl-hand directory in `robotino_bringup/robots`. I will check which is the correct file, and then remove `obotino_bringup/robots/kcl-hand` ok?

**Comment by ipa-nhg** [comment]
No, do not remove it please:

-  the kclhand.launch is the file that starts the kclhand_control driver.

- The folder robotino_bringup/robots/kcl-hand is the folder of a robot, like tuw-robotino2. This robot is only a hand, with a description, a launch file and a config folder. You can use it to test the hand, only the hand, on your laptop but using the same software and starting the same nodes that we start on the robotinos. 

I think it is useful to test hands during the setup and to debug errors.

**Comment by mzillich** [comment]
Ah, get it. Yes, having the hand itself as robot is useful. Cool, case closed.
