### ISSUE TITLE
Adapt the software to the new shell model

### ISSUE THREAD

**Issue by ipa-nhg** [squirrel-project/squirrel_robotino#178]
- [x] update the collision model of the arm to include the skin @ipa-nhg --> https://github.com/squirrel-project/squirrel_common/pull/165
- [x] define a folded position of the arm inside the shell @ipa-nhg  --> https://github.com/squirrel-project/squirrel_robotino/pull/173#issuecomment-275669767 
- [ ] update moveit configuration to attach the collision model of the shell @mzillich 
- [x] update the position of the hokuyo 
- [x] update the URDF to have a movable neck @ipa-nhg
- [x] update the position of the kinect
- [x] calibrate the robot with the new setup
- [ ] update the moveit configuration

**Comment by ghost** [comment]
@smhaller and me worked on it yesterday but had to basically deactivate all collisions with any arm links and the shell to get the robot moving; we observed sth very strange: with shell collisions the arm did not move, without it did - backwards: i have no idea whether this is related to moveit or the pose we use, but the robot generally did not "want" to plan a trajectory that allows him to approach the pose from the "front" by rotating its base. no clue how to fix this. For now UIBK will remove all collisions as otherwise not even kinesthetic teaching works...

**Comment by ipa-nhg** [comment]
@lokalmatador may I have an idea, are you using the 8 dof? if you rotate the base and the position is not being updated, moveit! thinks that the shell is on the front part of the robot and can't move the arm... could this be the case?

**Comment by ghost** [comment]
yeah, it was 8DoF. we did no rotate the base - the base should've rotated, but did not. also, i do not know whether positions (which positions - of the shell?) are updated or not - I assume they are, if not, that'd be bad, right? but that could explain it. however, we checked the robot' state from inside rviz, it had no collision and the shell was properly oriented.

**Comment by ipa-nhg** [comment]
I tested the models and moveit planner on simulation:

1. Using the current status of squirrel_driver, squirrel_robotino, squirrel_manipulation and starting :
```
roslaunch robotino_bringup_sim robot.launch robot:=tuw-robotino2
roslaunch tuw_moveit_config move_group.launch
```
I was able to plan but only forwards:  https://drive.google.com/open?id=0ByU-CIgXY6f6SjVTSE1DY1Utb2c


2. Set the 8dof to true https://github.com/squirrel-project/squirrel_robotino/blob/indigo_dev/robotino_bringup/robots/tuw-robotino2/urdf/robotino.urdf.xacro#L14 and starting again:
```
roslaunch robotino_bringup_sim robot.launch robot:=tuw-robotino2
roslaunch tuw_moveit_config move_group.launch
```
I am not able to plan and (the position of the base is wrong) , I am using on simulation the uibk_moveit_driver to use the 8 dof mode, the same as the real robot https://drive.google.com/open?id=0ByU-CIgXY6f6Qmw2ekdkWGxUcU0


P.S. didn't update the moveit model!!

**Comment by ghost** [comment]
I see; so could this be again related to the 8DoF mode not working properly? If yes, that'd be a bummer. Talk to @smhaller.

**Comment by ghost** [comment]
@Senka2112 do you have a guess why planning fails and the base is off?
@ipa-nhg do you assume its an error in the model or sth else?
at least TUW's robotino has the same issue, so it's not robot-specific.

**Comment by ipa-nhg** [comment]
The problem could be the driver (uibk_robot_driver) , the responsible of update the position of the base_link* , you can test it  just moving around the arm/base using the 8dof mode and check on RVIZ the positions.

also could be possible a conflict between the  driver and the robot_state_publisher if we set 8dof to true? I mean the robot_state_publisher give me different  transformations between base_link, base_linkx, base_linky, base_linkz and until the driver update it, the position is wrong and moveit is getting crazy? Save the messages from  /joint_states and check if you get multiple base_joints* position when you are not moving the base. 

Also maybe you have to set something for the moveit model, you can check the old moveit_config from Festo, we were last year able to plan with this configuration (6 dof)  having a shell collision model.
