### ISSUE TITLE
robotino_bringup with the new urdf

### ISSUE THREAD

**Issue by jibweb** [squirrel-project/squirrel_robotino#216]
I am not sure if I am doing something wrong, as I don't know much abut URDF, but running the bringup for tuw_robotino2.launch with the current version of this repo, I get:
```
... logging to /u/vienna/.ros/log/c587a078-b429-11e7-a2aa-00012e79a4f8/roslaunch-scrat-9659.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 696, in main
    eval_self_contained(doc)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 626, in eval_self_contained
    eval_all(doc.documentElement, macros, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 526, in eval_all
    (str(name), str(node.tagName)))
xacro.XacroException: Invalid parameter "base_neck_pitch" while expanding macro "xacro:shell"
while processing /u/vienna/catkin_ws/src/squirrel_robotino/robotino_bringup/robots/tuw-robotino2/launch/tuw-robotino2.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/u/vienna/catkin_ws/src/squirrel_robotino/robotino_bringup/robots/tuw-robotino2/urdf/robotin
o.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find robotino_bringup)/robots/$(arg robot)/urdf/robotino.urdf.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file

```

What is up with the base_neck_pitch ? The last version of the bringup that worked didn't have as many link defined in the properties.urdf.xacro, notably base_neck was not in there yet.

**Comment by ipa-nhg** [comment]
`base_neck_pitch` is a parameter which value is defined in the properties file https://github.com/squirrel-project/squirrel_robotino/blob/indigo_dev/robotino_bringup/robots/tuw-robotino2/urdf/properties.urdf.xacro#L39, this parameter is used to calibrate the robot being one of the outputs of the calibration software. are you sure that are using the current upstream version of `squirrel_robotino` and `squirrel_common`??

**Comment by jibweb** [comment]
So this was indeed related to the status of squirrel_common. It is on the `fix_joints_limits` branch
@ipa-nhg @lokalmatador @mzillich @smhaller  should I open a pull request with the changes from that branch ? It contains changes to `arm.urdf.xacro`, `base.urdf.xacro`, `shell.urdf.xacro` in robotino_description and the removal of ReturnJointStates.srv

**Comment by ghost** [comment]
I guess so, yes.

**Comment by ipa-nhg** [comment]
do you mean a local version?? just pull from squirrel-project and if still changes not committed, commit and open a PR please

**Comment by jibweb** [comment]
Here it is: squirrel-project/squirrel_common#236
