### ISSUE TITLE
laser limits

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_robotino#56]
@ipa-nhg I notice in rviz that quite a lot of laser readings are from the robot itself.
See the red dots here:
![rviz](https://cloud.githubusercontent.com/assets/4312487/8598860/7bf3bc00-265d-11e5-9df1-b48e188cefa5.png)
I think they do affect mapping quite a bit. How can we get rid of these? Move the laser forward a bit, as on the real robot? And limiting the scan angles?

**Comment by ipa-rmb** [comment]
Can this become closed?

**Comment by mzillich** [comment]
Yes, I will close this.
