### ISSUE TITLE
what is robotino_driver?

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_robotino#60]
Hi @ipa-nhg , what is actually in robotino_driver? Should this not be in squirrel_driver ..?

**Comment by ipa-nhg** [comment]
In order to have some consistency , we should keep robotino_drivers in squirrel_robotino. All the other components(for example hand or arm) have their own repository where the driver package is included

**Comment by mzillich** [comment]
yes, makes sense

**Comment by ipa-nhg** [comment]
Close the issue
