### ISSUE TITLE
robotino_arm_bringup

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_robotino#65]
Just started a fresh new version of squirrel_robotino.

Running `roslaunch robotino_bringup_sim robot.launch` I'm getting the following error
`raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: robotino_arm_bringup`

Apparently the package depends upon `robotino_arm_bringup` which is not part of `squirrel_robotino`

**Comment by ipa-nhg** [comment]
You need also the repository squirrel_robotino_arm. 
https://github.com/squirrel-project/squirrel_robotino_arm please follow  the Readme instructions top install the repository.
