### ISSUE TITLE
starting tuw robot with arm

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_robotino#95]
When starting tuw-robotino2, I get this error:
Any idea what is missing? All checked out fresh from squirrel-project.

> roslaunch robotino_bringup_sim robot.launch robot:=tuw-robotino2
> ...
> Traceback (most recent call last):
>   File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
>     xacro.main()
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/**init**.py", line 687, in main
>     process_includes(doc, os.path.dirname(args[0]))
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/**init**.py", line 246, in process_includes
>     filename_spec = eval_text(elt.getAttribute('filename'), {})
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/**init**.py", line 485, in eval_text
>     results.append(handle_extension(lex.next()[1][2:-1]))
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/**init**.py", line 473, in handle_extension
>     return eval_extension("$(%s)" % s)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/**init**.py", line 66, in eval_extension
>     return substitution_args.resolve_args(str, context=substitution_args_context, resolve_anon=False)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 312, in resolve_args
>     resolved = _resolve_args(resolved, context, resolve_anon, commands)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 325, in _resolve_args
>     resolved = commands[command](resolved, a, args, context)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 153, in _find
>     pkg_path = rp.get_path(args[0])
>   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 200, in get_path
>     raise ResourceNotFound(name, ros_paths=self._ros_paths)
> rospkg.common.ResourceNotFound: kclhand_description
> ROS path [0]=/opt/ros/indigo/share/ros
> ROS path [1]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/cf_control
> ROS path [2]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/robotino_arm_bringup
> ROS path [3]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/robotino_arm_description
> ROS path [4]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/robotino_arm_base_control
> ROS path [5]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_bringup
> ROS path [6]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_bringup_sim
> ROS path [7]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_calibration
> ROS path [8]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_description
> ROS path [9]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/robotino_description3
> ROS path [10]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_gazebo_worlds
> ROS path [11]=/home/michael.zillich/squirrel_ws/src/squirrel_common/robotino_msgs
> ROS path [12]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_safety
> ROS path [13]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_3d_mapping_msgs
> ROS path [14]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_common
> ROS path [15]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_kclhand_msgs
> ROS path [16]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_manipulation_msgs
> ROS path [17]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_localizer_msgs
> ROS path [18]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_navigation_msgs
> ROS path [19]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_mhand_msgs
> ROS path [20]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_object_perception_msgs
> ROS path [21]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_person_tracker_msgs
> ROS path [22]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_prediction_msgs
> ROS path [23]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_rgbd_mapping_msgs
> ROS path [24]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/squirrel_robotino
> ROS path [25]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_sketch_interface_msgs
> ROS path [26]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_speech_msgs
> ROS path [27]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/squirrel_robotino_arm
> ROS path [28]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_waypoint_msgs
> ROS path [29]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/robotino_arm_5dof_moveit_config
> ROS path [30]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/robotino_arm_6dof_moveit_config
> ROS path [31]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino_arm/robotino_arm_moveit_config
> ROS path [32]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_driver
> ROS path [33]=/home/michael.zillich/squirrel_ws/src/squirrel_common/squirrel_planning_knowledge_msgs
> ROS path [34]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_controller_configuration_gazebo
> ROS path [35]=/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_teleop
> ROS path [36]=/opt/ros/indigo/share
> ROS path [37]=/opt/ros/indigo/stacks
> while processing /home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_bringup_sim/robots/tuw-robotino2/tuw-robotino2.launch:
> Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/home/michael.zillich/squirrel_ws/src/squirrel_robotino/robotino_bringup/robots/tuw-robotino2/urdf/robotino.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find robotino_bringup)/robots/$(arg robot)/urdf/robotino.urdf.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by ipa-nhg** [comment]
--->  `rospkg.common.ResourceNotFound: kclhand_description` 

did you clone squirrel_kclhand repository?

**Comment by mzillich** [comment]
that was my first guess too. I have
src/squirrel_kclhand/

> git remote -v
> origin  git@github.com:squirrel-project/squirrel_kclhand.git (fetch)

**Comment by ipa-nhg** [comment]
what says `echo $ROS_PACKAGE_PATH` ?
and `roscd kclhand_description` ?

**Comment by mzillich** [comment]
`roscd kclhand_description` does not work.
I have:

```
src/squirrel_kclhand/
  kclhand_bringup
  ...
  kclhand_description
    package.xml:
       ...
       <name>kclhand_description</name>
```

odd. But ok, that seems to be the problem

**Comment by ipa-nhg** [comment]
I suggest you clean the workspace , source /opt/ros, build the repos and source the devel folder.

cd ~/squirrel_ws
rm -rf devel/ build/ install/
source /opt/ros/indigo/setup.bash
catkin_make 
source devel/setup.bash

It looks like you are setting some wrong ROS paths

**Comment by mzillich** [comment]
ok, that was it. some kcl hand dependencies were missing, and it did not get built!
works now, thanks!
