### ISSUE TITLE
Documentation for the scanner calibration

### ISSUE THREAD

**Issue by ipa-nhg** [squirrel-project/squirrel_robotino#98]
@federico-b can you please write some documentation about the calibration of the scanners? Just a small instructions readme, maybe you can add it to the point 2. of the robotino_calibration readme https://raw.githubusercontent.com/squirrel-project/squirrel_robotino/indigo_dev/robotino_calibration/readme.md

**Comment by ipa-rmb** [comment]
There is some documentation on it at https://github.com/federico-b/squirrel_nav/tree/laser_odom_calibration/laser_odom_calibration .

**Comment by ghost** [comment]
Hi,

yes that's some documentation. However it is still a super draft (I did it for Innsbruck a week ago). I'll double check it and create a request as soon as I'll be back home.

**Comment by ipa-rmb** [comment]
Thanks for your comment Federico, I just linked your readme from within the tutorial to allow people to get started at all. Once you have the proper documentation ready, please let me know to update my links.
